/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRoachRouteImport } from './routes/api/roach'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as ApiSupraPriceRouteImport } from './routes/api/supra-price'
import { Route as ApiVaultRouteImport } from './routes/api/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoachRoute = ApiRoachRouteImport.update({
  id: '/api/roach',
  path: '/api/roach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupraPriceRoute = ApiSupraPriceRouteImport.update({
  id: '/api/supra-price',
  path: '/api/supra-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultRoute = ApiVaultRouteImport.update({
  id: '/api/vault',
  path: '/api/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/roach': typeof ApiRoachRoute
  '/api/scan': typeof ApiScanRoute
  '/api/supra-price': typeof ApiSupraPriceRoute
  '/api/vault': typeof ApiVaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/roach': typeof ApiRoachRoute
  '/api/scan': typeof ApiScanRoute
  '/api/supra-price': typeof ApiSupraPriceRoute
  '/api/vault': typeof ApiVaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/roach': typeof ApiRoachRoute
  '/api/scan': typeof ApiScanRoute
  '/api/supra-price': typeof ApiSupraPriceRoute
  '/api/vault': typeof ApiVaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/roach' | '/api/scan' | '/api/supra-price' | '/api/vault'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/roach' | '/api/scan' | '/api/supra-price' | '/api/vault'
  id:
    | '__root__'
    | '/'
    | '/api/roach'
    | '/api/scan'
    | '/api/supra-price'
    | '/api/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoachRoute: typeof ApiRoachRoute
  ApiScanRoute: typeof ApiScanRoute
  ApiSupraPriceRoute: typeof ApiSupraPriceRoute
  ApiVaultRoute: typeof ApiVaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roach': {
      id: '/api/roach'
      path: '/api/roach'
      fullPath: '/api/roach'
      preLoaderRoute: typeof ApiRoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supra-price': {
      id: '/api/supra-price'
      path: '/api/supra-price'
      fullPath: '/api/supra-price'
      preLoaderRoute: typeof ApiSupraPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault': {
      id: '/api/vault'
      path: '/api/vault'
      fullPath: '/api/vault'
      preLoaderRoute: typeof ApiVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoachRoute: ApiRoachRoute,
  ApiScanRoute: ApiScanRoute,
  ApiSupraPriceRoute: ApiSupraPriceRoute,
  ApiVaultRoute: ApiVaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
